version: '3.7'

services:
  app:
    image: ruby:3.0
    volumes:
      - .:/app
    working_dir: /app
    command: bash
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BUNDLE_PATH: /app/.gems

  redis:
    image: redis:5.0.6
    command: --port 6379

