#!/bin/bash -e

command_name=$1
command_args=${@:2}

image_name="heartcheck-redis"

run() {
  args=${@:1}
  docker-compose run --rm -v $PWD:/heartcheck-redis app $args
}

case $command_name in
  setup)
    docker-compose build
    run bundle install
    ;;
  bash)
    run bash
    ;;
  bundle)
    run bundle install
    ;;
  console)
    run bin/console
    ;;
  rspec)
    run bundle exec rspec
    ;;
  usage)
    echo -e "Usage:\n"
    echo -e "heartcheck-redis bash       - access docker sh console"
    echo -e "heartcheck-redis bundle     - runs bundle install"
    echo -e "heartcheck-redis console    - runs a irb console"
    echo -e "heartcheck-redis rspec      - runs rspec"
    echo -e "heartcheck-redis setup      - setups docker image"
    ;;
  *)
    $0 usage
  ;;
esac

